// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInstalledPackages():Promise<Array<main.InstalledPackage>>;

export function SearchPackage(arg1:string):Promise<Array<main.PackageInfo>>;

export function UninstallPackage(arg1:string):Promise<void>;
