// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPackageInstalled(arg1) {
  return window['go']['main']['App']['CheckPackageInstalled'](arg1);
}

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function GetMultiplePackageInfo(arg1) {
  return window['go']['main']['App']['GetMultiplePackageInfo'](arg1);
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function SearchLocalPackage(arg1) {
  return window['go']['main']['App']['SearchLocalPackage'](arg1);
}

export function SearchPackage(arg1) {
  return window['go']['main']['App']['SearchPackage'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}
