// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function InstallApp(arg1) {
  return window['go']['main']['App']['InstallApp'](arg1);
}

export function SearchLocalPackage(arg1) {
  return window['go']['main']['App']['SearchLocalPackage'](arg1);
}

export function SearchPackage(arg1) {
  return window['go']['main']['App']['SearchPackage'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}
