// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPackageInstalled(arg1:string):Promise<boolean>;

export function GetAvailableUpdates():Promise<Array<main.UpdateInfo>>;

export function GetInstalledPackages():Promise<Array<main.PackageInfo>>;

export function GetMultiplePackageInfo(arg1:Array<string>):Promise<Array<main.PackageInfo>>;

export function HumanReadableSize(arg1:number):Promise<string>;

export function Install(arg1:string):Promise<void>;

export function SearchLocalPackage(arg1:string):Promise<boolean>;

export function SearchPackage(arg1:string):Promise<Array<main.PackageInfo>>;

export function Uninstall(arg1:string):Promise<void>;

export function UpdateAllPkg():Promise<void>;

export function UpdateSinglePkg(arg1:string):Promise<void>;
